{
  "hash": "b5e596bafe8d69129dbc3aba6c95f582",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Analísis bivariado\"\neditor: \n  markdown: \n    wrap: 72\n---\n\nEn los capítulos anteriores se estudiaron las características de una\nsola variable a la vez, analizando aspectos como la tendencia central,\nla dispersión, la posición y la forma de los datos. Sin embargo, en los\nproblemas reales rara vez las variables actúan de manera aislada. En la\npráctica, los fenómenos sociales, económicos, educativos, biológicos y\nadministrativos suelen depender de la interacción entre múltiples\nvariables.\n\nPor ejemplo, en educación puede surgir la pregunta de si un mayor número\nde horas de estudio se relaciona con mejores calificaciones; en salud,\nsi existe asociación entre el índice de masa corporal y la presión\narterial; o en economía, si el nivel de ingresos influye sobre el gasto\nfamiliar. Todas estas situaciones requieren estudiar simultáneamente dos\nvariables y comprender cómo se comportan conjuntamente.\n\nEl análisis bivariado corresponde precisamente al conjunto de técnicas\nestadísticas utilizadas para explorar, describir, cuantificar e\ninterpretar la relación entre dos variables medidas sobre las mismas\nunidades de análisis. A diferencia del análisis univariado, cuyo\npropósito es describir individualmente una variable, el análisis\nbivariado busca identificar patrones de asociación, dependencia o\npredicción entre variables.\n\nDependiendo de la naturaleza de las variables involucradas, el análisis\nbivariado puede abordar diferentes situaciones:\n\nrelaciones entre variables cuantitativas; asociaciones entre variables\ncategóricas; comparación de una variable cuantitativa entre categorías.\n\nEn este capítulo se desarrollan las principales herramientas del\nanálisis bivariado, incluyendo:\n\ndiagramas de dispersión, covarianza, correlación de Pearson, correlación\nde Spearman, tablas de contingencia, y regresión lineal simple.\n\nCada técnica será presentada desde una perspectiva teórica y\nposteriormente aplicada mediante ejemplos desarrollados en R utilizando\nun mismo conjunto de datos, con el propósito de facilitar la comprensión\nprogresiva del análisis estadístico y fortalecer el aprendizaje\nexperiencial. Es importante destacar que el análisis bivariado\nconstituye la base de técnicas estadísticas más avanzadas, como la\nregresión múltiple, el análisis multivariado y los modelos predictivos\nutilizados actualmente en ciencia de datos, inteligencia artificial y\nanalítica aplicada.\n\n## **Tipos de análisis bivariado**\n\nEl tipo de análisis bivariado que puede realizarse depende de la\nnaturaleza de las variables estudiadas. En estadística, las variables\npueden ser cuantitativas o categóricas, y cada combinación requiere\nherramientas específicas de exploración, visualización e interpretación.\n\nCuando ambas variables son cuantitativas, el interés suele centrarse en\nevaluar si existe asociación, dependencia o relación funcional entre\nellas. En estos casos se utilizan herramientas como diagramas de\ndispersión, covarianza, correlación y regresión lineal. Por ejemplo,\npuede analizarse la relación entre horas de estudio y calificación\nfinal, o entre peso corporal y estatura.\n\nSi ambas variables son categóricas, el objetivo principal consiste en\nestudiar asociaciones entre categorías o grupos. Para ello se emplean\ntablas de contingencia y medidas de asociación categórica. Un ejemplo\nfrecuente corresponde al análisis de la relación entre género y nivel de\nsatisfacción académica.\n\nTambién existen situaciones donde una variable es cuantitativa y la otra\ncategórica. En estos casos, el interés radica en comparar el\ncomportamiento de la variable numérica entre diferentes grupos o\ncategorías. Por ejemplo, comparar las calificaciones promedio entre\nhombres y mujeres, o analizar diferencias salariales entre regiones.\n\nLa siguiente tabla resume las principales combinaciones posibles en el\nanálisis bivariado:\n\n| Tipo de variable 1 | Tipo de variable 2 | Objetivo principal | Técnicas utilizadas |\n|------------------|------------------|------------------|------------------|\n| C uantitativa | C uantitativa | Evaluar asociación o predicción | Correlación, regresión, dispersión |\n| Categórica | Categórica | Analizar asociación entre categorías | Tablas de contingencia |\n| C uantitativa | Categórica | Comparar grupos | Boxplot, medias, comparación gráfica |\n\nComprender el tipo de variables involucradas constituye un paso\nfundamental antes de seleccionar cualquier técnica estadística, ya que\nuna elección incorrecta puede conducir a interpretaciones inadecuadas o\nresultados inconsistentes.\n\nEn este capítulo se abordarán ejemplos correspondientes a cada una de\nestas situaciones, integrando representaciones gráficas, medidas\nestadísticas y modelos básicos de análisis bivariado mediante\nimplementaciones desarrolladas en R.\n\n## Conjunto de datos de trabajo\n\nA lo largo de este capítulo se utilizará un mismo conjunto de datos con\nel propósito de ilustrar las diferentes técnicas de análisis bivariado\nde manera integrada y progresiva. El uso de un único dataset facilita la\ncomparación de resultados y permite comprender cómo distintas\nherramientas estadísticas pueden analizar una misma realidad desde\nperspectivas complementarias.\n\nLa base de datos contiene información correspondiente a estudiantes\nuniversitarios e incluye variables cuantitativas y categóricas, entre\nellas:\n\nhoras de estudio semanales, calificación final, horas de sueño, y\ngénero.\n\nEstas variables permiten desarrollar ejemplos relacionados con:\n\nrelaciones entre variables cuantitativas, asociaciones entre variables\ncategóricas, y comparación de grupos.\n\nEn términos pedagógicos, este enfoque favorece el aprendizaje\nexperiencial, ya que el estudiante puede observar cómo los conceptos\nteóricos se aplican directamente sobre datos reales mediante análisis\nreproducibles en R.\n\n### Carga de datos en R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(dplyr)\n\ndatos <- read_excel(\n  \"C:/R-Proyectos/estadistica-experiencial/data/bd_antropometricas.xlsx\"\n)\n\nhead(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 17\n  Clase Grupo Genero Altura_cm Peso_Kg Anchura_hombros_cm Long_Mano_cm\n  <chr> <chr> <chr>      <dbl>   <dbl>              <dbl>        <dbl>\n1 D     A     M            177      73                 49           19\n2 D     A     M            177      86                 45           19\n3 D     A     F            160      52                 37           16\n4 D     A     F            159      53                 38           16\n5 D     A     F            174      78                 41           18\n6 D     B     M            186      68                 44           19\n# ℹ 10 more variables: Lon_Palma_cm <dbl>, Ancho_Palma_cm <dbl>,\n#   Long_Brazo_cm <dbl>, Long_Antebrazo_cm <dbl>, Long_Pierna_cm <dbl>,\n#   Long_Pie_cm <dbl>, Curso <chr>, Talla_Dicotica <chr>, IMC_Dicotico <chr>,\n#   Mano_Dicotica <chr>\n```\n\n\n:::\n:::\n\n\n### Exploración inicial de variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Clase\"              \"Grupo\"              \"Genero\"            \n [4] \"Altura_cm\"          \"Peso_Kg\"            \"Anchura_hombros_cm\"\n [7] \"Long_Mano_cm\"       \"Lon_Palma_cm\"       \"Ancho_Palma_cm\"    \n[10] \"Long_Brazo_cm\"      \"Long_Antebrazo_cm\"  \"Long_Pierna_cm\"    \n[13] \"Long_Pie_cm\"        \"Curso\"              \"Talla_Dicotica\"    \n[16] \"IMC_Dicotico\"       \"Mano_Dicotica\"     \n```\n\n\n:::\n\n```{.r .cell-code}\nstr(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [260 × 17] (S3: tbl_df/tbl/data.frame)\n $ Clase             : chr [1:260] \"D\" \"D\" \"D\" \"D\" ...\n $ Grupo             : chr [1:260] \"A\" \"A\" \"A\" \"A\" ...\n $ Genero            : chr [1:260] \"M\" \"M\" \"F\" \"F\" ...\n $ Altura_cm         : num [1:260] 177 177 160 159 174 186 174 172 156 165 ...\n $ Peso_Kg           : num [1:260] 73 86 52 53 78 68 115 50 62 64 ...\n $ Anchura_hombros_cm: num [1:260] 49 45 37 38 41 44 49 42 42 44 ...\n $ Long_Mano_cm      : num [1:260] 19 19 16 16 18 19 21 19 19 18 ...\n $ Lon_Palma_cm      : num [1:260] 11 10 8 9 10 11 11.4 10.1 10 10 ...\n $ Ancho_Palma_cm    : num [1:260] 9 9 8 8 8.5 8 9 7 8 8 ...\n $ Long_Brazo_cm     : num [1:260] 62 59 54 52 59 74 80 76 69 70 ...\n $ Long_Antebrazo_cm : num [1:260] 31 31 27 27 29 29 28 26 26 27 ...\n $ Long_Pierna_cm    : num [1:260] 42.7 41.8 40.9 49.1 48 43.4 42.4 44.2 47.8 39.7 ...\n $ Long_Pie_cm       : num [1:260] 23.7 23.1 25.1 26.9 27 24 22.9 25.6 24.4 24.4 ...\n $ Curso             : chr [1:260] \"2020-1\" \"2020-1\" \"2020-1\" \"2020-1\" ...\n $ Talla_Dicotica    : chr [1:260] \"Alta\" \"Alta\" \"Baja\" \"Baja\" ...\n $ IMC_Dicotico      : chr [1:260] \"Normal+\" \"Normal+\" \"Normal+\" \"Normal+\" ...\n $ Mano_Dicotica     : chr [1:260] \"Grande\" \"Grande\" \"Pequeña\" \"Pequeña\" ...\n```\n\n\n:::\n:::\n\n\n## Diagrama de dispersión\n\nEl diagrama de dispersión, también conocido como nube de puntos, es una\nrepresentación gráfica utilizada para explorar la relación entre dos\nvariables cuantitativas. Cada punto del gráfico representa una\nobservación y su posición en el plano cartesiano depende de los valores\nregistrados para las variables $X$ y $Y$.\n\nEsta herramienta constituye generalmente el primer paso del análisis\nbivariado, ya que permite identificar visualmente patrones de\nasociación, tendencias, agrupamientos y posibles valores atípicos antes\nde aplicar medidas numéricas de correlación o modelos de regresión. A\npartir de un diagrama de dispersión pueden identificarse diferentes\ncomportamientos entre las variables:\n\n![Fuente: Autores](img/dispersion.jpg)\n\n#### Ejemplo en R\n\nEn el siguiente ejemplo se utiliza la base de datos antropométrica para\nanalizar la relación entre la estatura de los estudiantes y su peso\ncorporal. El objetivo consiste en explorar visualmente si existe\nasociación entre ambas variables mediante un diagrama de dispersión.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Librerías\nlibrary(readxl)\nlibrary(ggplot2)\n\n# Cargar base de datos\ndatos <- read_excel(\n  \"C:/R-Proyectos/estadistica-experiencial/data/bd_antropometricas.xlsx\"\n)\n\n# Diagrama de dispersión\nggplot(\n  datos,\n  \n  aes(\n    x = Altura_cm,\n    y = Peso_Kg,\n    color = Genero\n  )\n) +\n  \n  geom_point(\n    size = 3,\n    alpha = 0.75\n  ) +\n  \n  scale_color_manual(\n    values = c(\n      \"F\" = \"#D95F02\",\n      \"M\" = \"#1B9E77\"\n    )\n  ) +\n  \n  labs(\n    title = \"Relación entre altura y peso corporal\",\n    \n    subtitle = \"Distribución según género\",\n    \n    x = \"Altura (cm)\",\n    \n    y = \"Peso (kg)\",\n    \n    color = \"Género\",\n    \n    caption = \"Fuente: Base antropométrica prof. Miguel Pérez\"\n  ) +\n  \n  theme_minimal(base_size = 12) +\n  \n  theme(\n    plot.title = element_text(\n      face = \"bold\",\n      size = 15\n    ),\n    \n    plot.subtitle = element_text(\n      size = 11\n    ),\n    \n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](07-analisis-bivariado_files/figure-epub/unnamed-chunk-3-1.png)\n:::\n:::\n\n\n**Interpretación:** El diagrama de dispersión permite explorar\nvisualmente la relación entre la altura y el peso corporal de los\nestudiantes, diferenciando las observaciones según el género. En\ngeneral, se observa una tendencia positiva entre ambas variables,\nindicando que a mayores valores de altura tienden a presentarse mayores\nvalores de peso corporal.\n\nLa diferenciación por color facilita identificar posibles agrupamientos\nentre hombres y mujeres, evidenciando patrones distintos en la\ndistribución de las observaciones. Este tipo de visualización resulta\nútil para detectar comportamientos particulares dentro de subgrupos\npoblacionales y constituye una herramienta exploratoria fundamental\nantes de aplicar medidas numéricas de asociación o modelos estadísticos\nmás complejos.\n\n::: callout-warning\nEl **diagrama de dispersión** es principalmente una herramienta de\nanálisis exploratorio y visualización bivariada. NO es todavía una\ncorrelación numérica.\n:::\n\n## Prueba de normalidad Shapiro-Wilk\n\nLa prueba de Shapiro-Wilk permite evaluar si una variable cuantitativa\npresenta una distribución aproximadamente normal. En este caso, se\nanalizan las variables altura y peso corporal de los estudiantes.\n\nLa hipótesis nula ($H_0$​) establece que los datos siguen una\ndistribución normal, mientras que la hipótesis alternativa ($H_1$​)\nplantea que la distribución no es normal.\n\nLa decisión se toma a partir del valor $p$:\n\n-   si $p > 0.05$, no se rechaza la normalidad;\n\n-   si $p \\leq 0.05$, se concluye que la variable no presenta\n    distribución normal.\n\nEstas pruebas son importantes porque muchas técnicas estadísticas\nparamétricas, como la correlación de Pearson y la regresión lineal,\nasumen normalidad en los datos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Librerías\nlibrary(readxl)\nlibrary(dplyr)\nlibrary(purrr)\n\n# Cargar base de datos\ndatos <- read_excel(\n  \"C:/R-Proyectos/estadistica-experiencial/data/bd_antropometricas.xlsx\"\n)\n\n# Seleccionar variables numéricas\nvariables_numericas <- datos %>%\n  \n  select(where(is.numeric))\n\n# Aplicar Shapiro-Wilk a cada variable\nnormalidad <- map_df(\n  \n  names(variables_numericas),\n  \n  ~{\n    \n    prueba <- shapiro.test(\n      na.omit(variables_numericas[[.x]])\n    )\n    \n    data.frame(\n      Variable = .x,\n      W = round(prueba$statistic, 4),\n      p_value = round(prueba$p.value, 6),\n      \n      Normalidad = ifelse(\n        prueba$p.value > 0.05,\n        \"Sí presenta normalidad\",\n        \"No presenta normalidad\"\n      )\n    )\n  }\n)\n\n# Mostrar resultados\nnormalidad\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Variable      W  p_value             Normalidad\nW...1           Altura_cm 0.9753 0.000172 No presenta normalidad\nW...2             Peso_Kg 0.9040 0.000000 No presenta normalidad\nW...3  Anchura_hombros_cm 0.8824 0.000000 No presenta normalidad\nW...4        Long_Mano_cm 0.2747 0.000000 No presenta normalidad\nW...5        Lon_Palma_cm 0.9460 0.000000 No presenta normalidad\nW...6      Ancho_Palma_cm 0.9310 0.000000 No presenta normalidad\nW...7       Long_Brazo_cm 0.7635 0.000000 No presenta normalidad\nW...8   Long_Antebrazo_cm 0.7616 0.000000 No presenta normalidad\nW...9      Long_Pierna_cm 0.9950 0.564763 Sí presenta normalidad\nW...10        Long_Pie_cm 0.9914 0.134404 Sí presenta normalidad\n```\n\n\n:::\n:::\n\n\n## Cuando la variable presenta distribución normal\n\n**Interpretación:** Las variables **Long_Pierna_cm** y **Long_Pie_cm**\npresentan un comportamiento compatible con una distribución normal según\nla prueba de Shapiro-Wilk.\n\nPara la variable **Long_Pierna_cm**, se obtuvo un estadístico\n$W = 0.9950$ y un valor $p = 0.564763$. Debido a que el valor $p$ es\nmayor que $0.05$, no se rechaza la hipótesis nula de normalidad. Esto\nindica que la distribución de la longitud de la pierna no presenta\ndiferencias significativas respecto a una distribución normal.\n\nDe manera similar, la variable **Long_Pie_cm** presentó un estadístico\n$W = 0.9914$ y un valor $p = 0.134404$. Al ser también mayor que $0.05$,\nse concluye que la longitud del pie presenta una distribución\naproximadamente normal.\n\nEn términos prácticos, estos resultados sugieren que ambas variables\nantropométricas poseen distribuciones relativamente simétricas y sin\ndesviaciones extremas importantes, lo cual favorece la aplicación de\ntécnicas estadísticas paramétricas, como: correlación de Pearson,\npruebas t, análisis de regresión lineal e intervalos de confianza\nbasados en normalidad.\n\nAsimismo, el comportamiento normal de estas variables es coherente con\nmuchas mediciones biológicas y antropométricas, donde las\ncaracterísticas físicas de una población suelen distribuirse alrededor\nde un valor promedio central.\n\n### Correlación de Pearson\n\nLa correlación es una medida estadística utilizada para cuantificar la\nfuerza y la dirección de la relación entre dos variables cuantitativas.\nA diferencia del diagrama de dispersión, que permite explorar\nvisualmente el comportamiento conjunto de las variables, la correlación\nresume dicha relación mediante un valor numérico.\n\nEl coeficiente de correlación de Pearson se calcula como:\n\n$$\nr = \\frac{\\sum_{i=1}^{n}(x_i-\\bar{x})(y_i-\\bar{y})}\n{\\sqrt{\\sum_{i=1}^{n}(x_i-\\bar{x})^2 \\sum_{i=1}^{n}(y_i-\\bar{y})^2}}\n$$\n\nEl coeficiente de correlación indica qué tan estrechamente se relacionan\ndos variables y si dicha relación es positiva, negativa o inexistente.\n\n![Fuente: autores](img/correlacion.jpg)\n\n#### Ejemplo en R\n\nEn el siguiente ejemplo se calcula la correlación entre altura y peso\ncorporal utilizando la base de datos antropométrica.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Librerías\nlibrary(readxl)\nlibrary(ggplot2)\n\n# Cargar base de datos\ndatos <- read_excel(\n  \"C:/R-Proyectos/estadistica-experiencial/data/bd_antropometricas.xlsx\"\n)\n\n# Calcular correlación\nr <- cor(\n  datos$Long_Pierna_cm,\n  datos$Long_Pie_cm,\n  \n  method = \"pearson\",\n  \n  use = \"complete.obs\"\n)\n\n# Gráfico\nggplot(\n  datos,\n  \n  aes(\n    x = Long_Pierna_cm,\n    y = Long_Pie_cm,\n    color = Genero\n  )\n) +\n  \n  geom_point(\n    size = 3,\n    alpha = 0.75\n  ) +\n  \n  scale_color_manual(\n    values = c(\n      \"F\" = \"#D95F02\",\n      \"M\" = \"#1B9E77\"\n    )\n  ) +\n  \n  geom_smooth(\n    method = \"lm\",\n    se = FALSE,\n    color = \"black\",\n    linewidth = 1\n  ) +\n  \n  annotate(\n    \"text\",\n    \n    x = min(datos$Long_Pierna_cm) + 5,\n    \n    y = max(datos$Long_Pie_cm) - 5,\n    \n    label = paste0(\n      \"r = \",\n      round(r, 3)\n    ),\n    \n    size = 5,\n    \n    fontface = \"bold\",\n    \n    color = \"black\"\n  ) +\n  \n  labs(\n    title = \"Relación entre Longitud Pierna y Longitud pie\",\n    \n    subtitle = \"Diagrama de dispersión y correlación de Pearson\",\n    \n    x = \"Longitud Pierna (cm)\",\n    \n    y = \"Longitud pie (cm)\",\n    \n    color = \"Género\",\n    \n    caption = \"Fuente: Base antropométrica Prof. Miguel Pérez\"\n  ) +\n  \n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](07-analisis-bivariado_files/figure-epub/unnamed-chunk-5-1.png)\n:::\n:::\n\n\n**Interpretación:** El diagrama de dispersión permite explorar la\nrelación entre la longitud de la pierna y la longitud del pie en los\nestudiantes, diferenciando las observaciones según el género.\nVisualmente, los puntos se encuentran ampliamente dispersos y no\nmuestran una tendencia lineal clara entre ambas variables.\n\nEl **coeficiente de correlación de Pearson** obtenido ($r = 0.012$)\nindica una **asociación lineal prácticamente nula entre la longitud de\nla pierna y la longitud del pie**. Este valor, al encontrarse muy\ncercano a cero, sugiere que el aumento en una de las variables no se\nrelaciona de manera consistente con cambios en la otra dentro de la\nmuestra analizada.\n\nAsimismo, la línea de tendencia horizontal observada en el gráfico\nconfirma la ausencia de una relación lineal significativa. Aunque\nexisten diferencias naturales entre hombres y mujeres en la distribución\nde las observaciones, dichas variaciones no generan un patrón de\nasociación fuerte entre las variables estudiadas.\n\nEn términos prácticos, estos resultados indican que la longitud de la\npierna no constituye un buen predictor lineal de la longitud del pie en\nesta población específica. Este tipo de análisis es importante porque\ndemuestra que no todas las variables antropométricas presentan\nrelaciones lineales fuertes, incluso cuando pertenecen a una misma\ndimensión biológica..\n\n## Cuando la variable no presenta distribución normal\n\n**Interpretación Altura_cm y Peso_Kg:** La prueba de Shapiro-Wilk indica\nque ninguna de las dos variables presenta una distribución normal al\nnivel de significancia del 5 %.\n\nPara la variable **Altura_cm**, se obtuvo un estadístico $W = 0.9752$ y\nun valor $p = 0.000171$. Debido a que el valor $p$ es menor que $0.05$,\nse rechaza la hipótesis nula de normalidad, concluyendo que la\ndistribución de la altura difiere significativamente de una distribución\nnormal.\n\nDe manera similar, para la variable **Peso_Kg**, el estadístico obtenido\nfue $W = 0.9040$ con un valor $p = 7.916 \\times 10^{-12}$, valor\nextremadamente pequeño que también conduce al rechazo de la hipótesis de\nnormalidad. Esto indica que la distribución del peso corporal presenta\ndesviaciones importantes respecto a la normalidad.\n\nEn términos prácticos, estos resultados sugieren que las variables\nantropométricas analizadas no cumplen completamente el supuesto de\nnormalidad requerido por algunas técnicas paramétricas. Por esta razón,\nen determinados contextos podría ser recomendable complementar el\nanálisis utilizando métodos no paramétricos, como la correlación de\nSpearman, especialmente si existen valores extremos o distribuciones\nasimétricas.\n\n### Correlación de Spearman\n\nLa correlación de Spearman es una medida estadística utilizada para\nevaluar la asociación entre dos variables ordinales o cuantitativas\ncuando no se cumplen los supuestos de normalidad o linealidad requeridos\npor la correlación de Pearson.\n\nA diferencia de Pearson, Spearman no trabaja directamente con los\nvalores originales de las variables, sino con sus rangos o posiciones\ndentro de la distribución. Por esta razón, se considera una medida no\nparamétrica de asociación.\n\n![Fuente: autores](img/corspearman.jpg)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Librerías\nlibrary(readxl)\nlibrary(ggplot2)\nlibrary(dplyr)\n\n# Cargar base de datos\ndatos <- read_excel(\n  \"C:/R-Proyectos/estadistica-experiencial/data/bd_antropometricas.xlsx\"\n)\n\n# Correlación por género\ndatos %>%\n  \n  group_by(Genero) %>%\n  \n  summarise(\n    Correlacion = cor(\n      Altura_cm,\n      Peso_Kg,\n      \n      method = \"spearman\",\n      \n      use = \"complete.obs\"\n    )\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  Genero Correlacion\n  <chr>        <dbl>\n1 F           0.0657\n2 M           0.178 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Diagrama de dispersión por género\nggplot(\n  datos,\n  \n  aes(\n    x = Altura_cm,\n    y = Peso_Kg,\n    color = Genero\n  )\n) +\n  \n  geom_point(\n    size = 3,\n    alpha = 0.75\n  ) +\n  \n  geom_smooth(\n    method = \"lm\",\n    se = FALSE,\n    linewidth = 1\n  ) +\n  \n  scale_color_manual(\n    values = c(\n      \"F\" = \"#D95F02\",\n      \"M\" = \"#1B9E77\"\n    )\n  ) +\n  \n  labs(\n    title = \"Relación entre altura y peso corporal según género\",\n    \n    subtitle = \"Comparación de patrones de asociación\",\n    \n    x = \"Altura (cm)\",\n    \n    y = \"Peso (kg)\",\n    \n    color = \"Género\",\n    \n    caption = \"Fuente: Base antropométrica\"\n  ) +\n  \n  theme_minimal(base_size = 12) +\n  \n  theme(\n    plot.title = element_text(\n      face = \"bold\",\n      size = 15\n    ),\n    \n    plot.subtitle = element_text(\n      size = 11\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](07-analisis-bivariado_files/figure-epub/unnamed-chunk-6-1.png)\n:::\n:::\n\n\n### Covarianza\n\nLa covarianza es una medida estadística utilizada para evaluar cómo\nvarían conjuntamente dos variables cuantitativas respecto a sus medias.\nEsta medida permite identificar si ambas variables tienden a aumentar\nsimultáneamente, disminuir conjuntamente o comportarse de manera\nindependiente.\n\nLa covarianza constituye uno de los fundamentos matemáticos de la\ncorrelación lineal y de la regresión.\n\n![Fuente: autores](img/covarianza.png)\n\nEjercicio en R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\n\n# Cargar base de datos\ndatos <- read_excel(\n  \"C:/R-Proyectos/estadistica-experiencial/data/bd_antropometricas.xlsx\"\n)\n\n# Covarianza\ncov(\n  datos$Long_Pierna_cm,\n  datos$Long_Pie_cm,\n  \n  use = \"complete.obs\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06261345\n```\n\n\n:::\n:::\n\n\n**Interpetación:** La covarianza calculada ($r = 0.062$) entre la\nlongitud de la pierna y la longitud del pie presenta un valor cercano a\ncero, indicando que ambas variables no muestran una variación conjunta\nimportante dentro de la muestra analizada.\n\nEste resultado coincide con el **análisis de correlación de Pearson**\npreviamente realizado ($r = 0.012$), donde también se evidenció una\nrelación lineal prácticamente nula entre las variables. En términos\nprácticos, los cambios en la longitud de la pierna no se asocian de\nmanera consistente con cambios en la longitud del pie en los estudiantes\nevaluados.\n\nAsimismo, este ejemplo permite comprender que no todas las variables\nantropométricas presentan asociaciones lineales fuertes, incluso cuando\npertenecen a dimensiones corporales relacionadas.\n\n### Tablas de contingencia\n\nLas tablas de contingencia son herramientas estadísticas utilizadas para\nresumir y analizar la relación entre dos variables categóricas. Estas\ntablas permiten organizar las frecuencias observadas según las\ndiferentes combinaciones de categorías presentes en las variables\nestudiadas.\n\nTambién son conocidas como: tablas cruzadas, tablas de doble entrada o\ntablas de asociación.\n\nSu principal objetivo consiste en identificar posibles patrones de\nrelación o dependencia entre categorías.\n\n## Estructura general\n\nUna tabla de contingencia distribuye las observaciones en filas y\ncolumnas:\n\n|              | Categoría B1 | Categoría B2 | Total        |\n|--------------|--------------|--------------|--------------|\n| Categoría A1 | $f_{11}$​     | $f_{12}$​     | $f_{1\\cdot}$​ |\n| Categoría A2 | $f_{21}$​     | $f_{22}$​     | $f_{2\\cdot}$​ |\n| Total        | $f_{\\cdot1}$​ | $f_{\\cdot2}$​ | $n$          |\n\ndonde:\n\n-   las filas representan categorías de una variable;\n\n-   las columnas representan categorías de la otra variable;\n\n-   cada celda contiene la frecuencia observada.\n\n## Interpretación\n\nLas tablas de contingencia permiten comparar frecuencias entre grupos;\nidentificar asociaciones entre categorías; calcular porcentajes\nconjuntos; analizar patrones poblacionales; servir como base para\npruebas como Chi-cuadrado. Cuando las proporciones observadas son\nsimilares entre categorías, puede inferirse independencia entre las\nvariables. En cambio, diferencias importantes sugieren posibles\nasociaciones.\n\n## Ejemplo contextual\n\nEn estudios educativos puede analizarse la relación entre género y\naprobación académica; modalidad de estudio y rendimiento o nivel\nsocioeconómico y acceso tecnológico. En salud tabaquismo y enfermedad;\nclasificación nutricional y actividad física.\n\n## Ejemplo en R\n\nEn el siguiente ejemplo se construye una tabla de contingencia entre\ngénero y grupo académico utilizando la base antropométrica.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(dplyr)\nlibrary(janitor)\nlibrary(knitr)\nlibrary(kableExtra)\n\n# Cargar base de datos\ndatos <- read_excel(\n  \"C:/R-Proyectos/estadistica-experiencial/data/bd_antropometricas.xlsx\"\n)\n\n#====================================================\n# 1. Género vs Talla dicotómica\n#====================================================\n\ndatos %>%\n  \n  tabyl(\n    Genero,\n    Talla_Dicotica\n  ) %>%\n  \n  adorn_totals(c(\"row\", \"col\")) %>%\n  \n  adorn_percentages(\"row\") %>%\n  \n  adorn_pct_formatting(digits = 1) %>%\n  \n  adorn_ns(position = \"front\") %>%\n  \n  kable(\n    caption = \"Tabla de contingencia: Género y talla dicotómica\",\n    align = \"c\"\n  ) %>%\n  \n  kable_styling(\n    full_width = FALSE,\n    bootstrap_options = c(\n      \"striped\",\n      \"hover\",\n      \"condensed\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Tabla de contingencia: Género y talla dicotómica</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Genero </th>\n   <th style=\"text-align:center;\"> Alta </th>\n   <th style=\"text-align:center;\"> Baja </th>\n   <th style=\"text-align:center;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> F </td>\n   <td style=\"text-align:center;\"> 23 (11.1%) </td>\n   <td style=\"text-align:center;\"> 185 (88.9%) </td>\n   <td style=\"text-align:center;\"> 208 (100.0%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> M </td>\n   <td style=\"text-align:center;\"> 30 (57.7%) </td>\n   <td style=\"text-align:center;\"> 22 (42.3%) </td>\n   <td style=\"text-align:center;\"> 52 (100.0%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Total </td>\n   <td style=\"text-align:center;\"> 53 (20.4%) </td>\n   <td style=\"text-align:center;\"> 207 (79.6%) </td>\n   <td style=\"text-align:center;\"> 260 (100.0%) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\n#====================================================\n# 2. Género vs IMC dicotómico\n#====================================================\n\ndatos %>%\n  \n  tabyl(\n    Genero,\n    IMC_Dicotico\n  ) %>%\n  \n  adorn_totals(c(\"row\", \"col\")) %>%\n  \n  adorn_percentages(\"row\") %>%\n  \n  adorn_pct_formatting(digits = 1) %>%\n  \n  adorn_ns(position = \"front\") %>%\n  \n  kable(\n    caption = \"Tabla de contingencia: Género e IMC dicotómico\",\n    align = \"c\"\n  ) %>%\n  \n  kable_styling(\n    full_width = FALSE,\n    bootstrap_options = c(\n      \"striped\",\n      \"hover\",\n      \"condensed\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Tabla de contingencia: Género e IMC dicotómico</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Genero </th>\n   <th style=\"text-align:center;\"> Bajo_Peso </th>\n   <th style=\"text-align:center;\"> Normal+ </th>\n   <th style=\"text-align:center;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> F </td>\n   <td style=\"text-align:center;\"> 127 (61.1%) </td>\n   <td style=\"text-align:center;\"> 81 (38.9%) </td>\n   <td style=\"text-align:center;\"> 208 (100.0%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> M </td>\n   <td style=\"text-align:center;\"> 10 (19.2%) </td>\n   <td style=\"text-align:center;\"> 42 (80.8%) </td>\n   <td style=\"text-align:center;\"> 52 (100.0%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Total </td>\n   <td style=\"text-align:center;\"> 137 (52.7%) </td>\n   <td style=\"text-align:center;\"> 123 (47.3%) </td>\n   <td style=\"text-align:center;\"> 260 (100.0%) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\n#====================================================\n# 3. Género vs Tamaño de mano\n#====================================================\n\ndatos %>%\n  \n  tabyl(\n    Genero,\n    Mano_Dicotica\n  ) %>%\n  \n  adorn_totals(c(\"row\", \"col\")) %>%\n  \n  adorn_percentages(\"row\") %>%\n  \n  adorn_pct_formatting(digits = 1) %>%\n  \n  adorn_ns(position = \"front\") %>%\n  \n  kable(\n    caption = \"Tabla de contingencia: Género y tamaño de mano\",\n    align = \"c\"\n  ) %>%\n  \n  kable_styling(\n    full_width = FALSE,\n    bootstrap_options = c(\n      \"striped\",\n      \"hover\",\n      \"condensed\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Tabla de contingencia: Género y tamaño de mano</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Genero </th>\n   <th style=\"text-align:center;\"> Grande </th>\n   <th style=\"text-align:center;\"> Pequeña </th>\n   <th style=\"text-align:center;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> F </td>\n   <td style=\"text-align:center;\"> 26 (12.5%) </td>\n   <td style=\"text-align:center;\"> 182 (87.5%) </td>\n   <td style=\"text-align:center;\"> 208 (100.0%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> M </td>\n   <td style=\"text-align:center;\"> 38 (73.1%) </td>\n   <td style=\"text-align:center;\"> 14 (26.9%) </td>\n   <td style=\"text-align:center;\"> 52 (100.0%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Total </td>\n   <td style=\"text-align:center;\"> 64 (24.6%) </td>\n   <td style=\"text-align:center;\"> 196 (75.4%) </td>\n   <td style=\"text-align:center;\"> 260 (100.0%) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Interpretación:** En términos generales, el 88.9 % de las mujeres se\nclasifican dentro del rango normal de IMC y el 11.1 % presenta sobrepeso\nu obesidad. En contraste, entre los hombres solo el 48.1 % presenta IMC\nnormal, mientras que el 51.9 % se ubica en la categoría de\nsobrepeso-obesidad. Considerando el total de la muestra, el 80.8 % de\nlos estudiantes presenta un IMC normal y el 19.2 % presenta sobrepeso u\nobesidad.\n\nEstos resultados sugieren una posible asociación entre el género y la\nclasificación del IMC, evidenciando una mayor proporción de\nsobrepeso-obesidad en los hombres respecto a las mujeres dentro de la\npoblación analizada. Las tablas de contingencia permiten identificar\neste tipo de patrones descriptivos y constituyen la base para\nposteriores análisis inferenciales, como la prueba Chi-cuadrado de\nindependencia.\n\n### Laboratorio experiencial:\n\n**¿Existe relación entre la altura y el peso corporal?**\n\n**Situación problema:** Un grupo de estudiantes de fisioterapia desea\nanalizar si la altura corporal se relaciona con el peso de los\nestudiantes universitarios. Para ello, se recolectó información\nantropométrica de hombres y mujeres de diferentes semestres académicos.\n\n**Objetivo del análisis**\n\nDeterminar: si existe relación entre altura y peso; la dirección de la\nrelación; la fuerza de la asociación y si el género modifica visualmente\nel comportamiento de los datos.\n\n### Actividades del estudiante\n\nParte 1 — Exploración visual\n\nPreguntas\n\n¿Qué tipo de relación observa en el diagrama? positiva, negativa, nula,\nurvilínea. \\\n¿La relación parece fuerte o débil? \\\n¿Existen valores atípicos?\\\n¿Se observan diferencias entre hombres y mujeres?\n\nParte 2 — Correlación\n\nCalcule: correlación de Pearson y correlación de Spearman.\n\nPreguntas\n\n¿Los coeficientes son similares? \\\n¿Cuál considera más apropiado según la distribución de los datos? \\\n¿Puede afirmarse causalidad?\n\nParte 3 — Interpretación aplicada\n\nUn investigador afirma que “Los estudiantes más altos necesariamente\npesan más”.\n\nPreguntas críticas\n\n¿La correlación encontrada permite afirmar eso?\n\n¿Qué limitaciones tiene el análisis?\n\n¿Qué otras variables podrían influir?\n",
    "supporting": [
      "07-analisis-bivariado_files\\figure-epub"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}