{
  "hash": "19f516069f739a7bbb00e441435f817f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Análisis de asociación entre variables\"\neditor: \n  markdown: \n    wrap: 72\n---\n\nEn los capítulos anteriores se estudiaron las características de las\nvariables de manera individual, considerando aspectos como la tendencia\ncentral, la dispersión, la posición y la forma de las distribuciones.\nSin embargo, en los problemas reales las variables rara vez se comportan\nde manera aislada. Con frecuencia, el interés estadístico consiste en\ncomprender **cómo dos o más características se relacionan, varían\nconjuntamente o permiten explicar el comportamiento de un fenómeno**.\n\nPor ejemplo, en un estudio antropométrico puede resultar de interés\nestablecer si la **altura corporal se relaciona con el peso**, si\ndeterminadas medidas corporales presentan patrones conjuntos, si existen\ndiferencias entre grupos o si algunas características pueden contribuir\na explicar el comportamiento de otra variable. Este tipo de preguntas\nrequiere pasar de la descripción individual de los datos al estudio de\nlas **relaciones y asociaciones entre variables**.\n\nEl **análisis de asociación** reúne herramientas estadísticas orientadas\na explorar, describir, cuantificar e interpretar estas relaciones.\nCuando el estudio se concentra específicamente en dos variables se habla\nde **análisis bivariado**. Dependiendo de la naturaleza de las variables\ny del propósito del análisis, pueden estudiarse relaciones entre\nvariables cuantitativas, asociaciones entre variables categóricas,\ndiferencias entre grupos o relaciones de tipo explicativo y predictivo.\n\nEs importante distinguir que **asociación no significa causalidad**.\nIdentificar que dos variables presentan un patrón conjunto no implica\nque una sea necesariamente la causa de la otra. La interpretación debe\nrealizarse considerando el contexto del estudio, el diseño mediante el\ncual se obtuvieron los datos y las posibles variables adicionales\ninvolucradas.\n\nEn este capítulo se desarrollarán herramientas como los **diagramas de\ndispersión, la covarianza, la correlación de Pearson, la correlación de\nSpearman, las tablas de contingencia y los modelos de regresión\nlineal**. Estas técnicas permiten estudiar la dirección, intensidad y\nestructura de las relaciones observadas, así como construir modelos\nbásicos para describir o explicar el comportamiento conjunto de las\nvariables.\n\nEl capítulo utilizará una **base de datos antropométrica de estudiantes\nuniversitarios**, que contiene variables cuantitativas y categóricas\nrelacionadas con características corporales. A partir de estos datos se\ndesarrollarán ejemplos reproducibles en R que permitirán conectar\nprogresivamente la representación gráfica, las medidas de asociación y\nlos modelos estadísticos.\n\nEl enfoque será fundamentalmente experiencial: cada concepto será\nacompañado por su interpretación, representación gráfica y aplicación\ncomputacional. De esta manera, el estudiante podrá avanzar desde una\npregunta sobre la relación entre variables hasta la selección de la\ntécnica estadística apropiada, su implementación en R y la\ninterpretación de los resultados.\n\nEste análisis constituye además una transición hacia métodos\nestadísticos de mayor complejidad. La comprensión de las relaciones\nentre variables proporciona fundamentos para estudiar posteriormente\nmodelos de regresión múltiple, técnicas multivariadas y procedimientos\nutilizados en analítica de datos y modelamiento estadístico.\n\n## Tipos de análisis de asociación según la naturaleza de las variables\n\nLa técnica estadística apropiada para estudiar una asociación depende\ntanto de la **naturaleza de las variables** como del **objetivo del\nanálisis**. Antes de calcular cualquier medida o ajustar un modelo, es\nnecesario identificar si las variables son cuantitativas o categóricas y\ndeterminar qué tipo de relación se desea explorar.\n\nCuando ambas variables son cuantitativas, el interés suele centrarse en\nevaluar si existe asociación, dependencia o relación funcional entre\nellas. En estos casos se utilizan herramientas como diagramas de\ndispersión, covarianza, correlación y regresión lineal. Por ejemplo,\npuede analizarse la relación entre horas de estudio y calificación\nfinal, o entre peso corporal y estatura.\n\nSi ambas variables son categóricas, el objetivo principal consiste en\nestudiar asociaciones entre categorías o grupos. Para ello se emplean\ntablas de contingencia y medidas de asociación categórica. Un ejemplo\nfrecuente corresponde al análisis de la relación entre género y nivel de\nsatisfacción académica.\n\nTambién existen situaciones donde una variable es cuantitativa y la otra\ncategórica. En estos casos, el interés radica en comparar el\ncomportamiento de la variable numérica entre diferentes grupos o\ncategorías. Por ejemplo, comparar las calificaciones promedio entre\nhombres y mujeres, o analizar diferencias salariales entre regiones.\n\nLa siguiente tabla resume las principales situaciones que pueden\npresentarse en el análisis de asociación:\n\n| Variables involucradas | Pregunta principal | Herramientas iniciales |\n|----|----|----|\n| Cuantitativa -- Cuantitativa | ¿Existe relación?, ¿en qué dirección y con qué intensidad? | Dispersión, covarianza, Pearson, Spearman, regresión |\n| Categórica -- Categórica | ¿Las categorías presentan asociación? | Tablas de contingencia y medidas o pruebas de asociación |\n| Cuantitativa -- Categórica | ¿La distribución de la variable cuantitativa cambia entre grupos? | Boxplot, estadísticos por grupo y comparación |\n| Una respuesta y varias explicativas | ¿Varias variables contribuyen conjuntamente a explicar una respuesta? | Regresión lineal múltiple |\n\nComprender el tipo de variables involucradas constituye un paso\nfundamental antes de seleccionar cualquier técnica estadística, ya que\nuna elección incorrecta puede conducir a interpretaciones inadecuadas o\nresultados inconsistentes.\n\nEn este capítulo se abordarán ejemplos correspondientes a varias de\nestas situaciones, integrando representaciones gráficas, medidas de\nasociación y modelos estadísticos básicos mediante implementaciones\ndesarrolladas en R.\n\n## Ruta conceptual del capítulo\n\nEl recorrido propuesto sigue una secuencia progresiva:\n\n**explorar visualmente → cuantificar la variación conjunta →\nestandarizar la asociación → modelar la relación → estudiar asociaciones\nentre categorías**.\n\nEsta secuencia permite comprender no solo cómo calcular cada\nestadístico, sino también qué pregunta responde, bajo qué condiciones\npuede utilizarse y cómo interpretar sus resultados dentro del contexto\ndel problema.\n\n## Conjunto de datos de trabajo\n\nA lo largo de este capítulo se utilizará un mismo conjunto de datos con\nel propósito de ilustrar las diferentes técnicas de análisis de\nasociación de manera integrada y progresiva. El uso de una misma base\nfacilita la comparación de resultados y permite comprender cómo\ndistintas herramientas estadísticas pueden estudiar una realidad desde\nperspectivas complementarias.\n\nLa base contiene información antropométrica correspondiente a\nestudiantes universitarios e incluye variables cuantitativas y\ncategóricas. Entre las variables utilizadas en los ejemplos del capítulo\nse encuentran la **altura**, el **peso corporal**, el **índice de masa\ncorporal (IMC)**, la **longitud de la pierna**, la **longitud del pie**,\nla **longitud de la mano** y el **género**, además de variables\nderivadas de clasificación antropométrica presentes en el conjunto de\ndatos.\n\nEstas variables permiten desarrollar ejemplos de relaciones entre\nvariables cuantitativas, asociaciones entre variables categóricas,\ncomparaciones entre grupos y modelos de regresión.\n\nEn términos pedagógicos, este enfoque favorece el aprendizaje\nexperiencial, ya que el estudiante puede observar cómo los conceptos\nteóricos se aplican directamente sobre datos reales mediante análisis\nreproducibles en R.\n\n## Carga de datos en R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(dplyr)\n\ndatos <- read_excel(\n  \"data/bd_antropometricas.xlsx\"\n)\n\nhead(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 17\n  Clase Grupo Genero Altura_cm Peso_Kg Anchura_hombros_cm Long_Mano_cm\n  <chr> <chr> <chr>      <dbl>   <dbl>              <dbl>        <dbl>\n1 D     A     M            177      73                 49           19\n2 D     A     M            177      86                 45           19\n3 D     A     F            160      52                 37           16\n4 D     A     F            159      53                 38           16\n5 D     A     F            174      78                 41           18\n6 D     B     M            186      68                 44           19\n# ℹ 10 more variables: Lon_Palma_cm <dbl>, Ancho_Palma_cm <dbl>,\n#   Long_Brazo_cm <dbl>, Long_Antebrazo_cm <dbl>, Long_Pierna_cm <dbl>,\n#   Long_Pie_cm <dbl>, Curso <chr>, Talla_Dicotica <chr>, IMC_Dicotico <chr>,\n#   Mano_Dicotica <chr>\n```\n\n\n:::\n:::\n\n\n## Exploración inicial de variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Clase\"              \"Grupo\"              \"Genero\"            \n [4] \"Altura_cm\"          \"Peso_Kg\"            \"Anchura_hombros_cm\"\n [7] \"Long_Mano_cm\"       \"Lon_Palma_cm\"       \"Ancho_Palma_cm\"    \n[10] \"Long_Brazo_cm\"      \"Long_Antebrazo_cm\"  \"Long_Pierna_cm\"    \n[13] \"Long_Pie_cm\"        \"Curso\"              \"Talla_Dicotica\"    \n[16] \"IMC_Dicotico\"       \"Mano_Dicotica\"     \n```\n\n\n:::\n\n```{.r .cell-code}\nstr(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [260 × 17] (S3: tbl_df/tbl/data.frame)\n $ Clase             : chr [1:260] \"D\" \"D\" \"D\" \"D\" ...\n $ Grupo             : chr [1:260] \"A\" \"A\" \"A\" \"A\" ...\n $ Genero            : chr [1:260] \"M\" \"M\" \"F\" \"F\" ...\n $ Altura_cm         : num [1:260] 177 177 160 159 174 186 174 172 156 165 ...\n $ Peso_Kg           : num [1:260] 73 86 52 53 78 68 115 50 62 64 ...\n $ Anchura_hombros_cm: num [1:260] 49 45 37 38 41 44 49 42 42 44 ...\n $ Long_Mano_cm      : num [1:260] 19 19 16 16 18 19 21 19 19 18 ...\n $ Lon_Palma_cm      : num [1:260] 11 10 8 9 10 11 11.4 10.1 10 10 ...\n $ Ancho_Palma_cm    : num [1:260] 9 9 8 8 8.5 8 9 7 8 8 ...\n $ Long_Brazo_cm     : num [1:260] 62 59 54 52 59 74 80 76 69 70 ...\n $ Long_Antebrazo_cm : num [1:260] 31 31 27 27 29 29 28 26 26 27 ...\n $ Long_Pierna_cm    : num [1:260] 42.7 41.8 40.9 49.1 48 43.4 42.4 44.2 47.8 39.7 ...\n $ Long_Pie_cm       : num [1:260] 23.7 23.1 25.1 26.9 27 24 22.9 25.6 24.4 24.4 ...\n $ Curso             : chr [1:260] \"2020-1\" \"2020-1\" \"2020-1\" \"2020-1\" ...\n $ Talla_Dicotica    : chr [1:260] \"Alta\" \"Alta\" \"Baja\" \"Baja\" ...\n $ IMC_Dicotico      : chr [1:260] \"Normal+\" \"Normal+\" \"Normal+\" \"Normal+\" ...\n $ Mano_Dicotica     : chr [1:260] \"Grande\" \"Grande\" \"Pequeña\" \"Pequeña\" ...\n```\n\n\n:::\n:::\n\n\n## Evaluación de supuestos\n\n### Variables cuantitativas continuas\n\nLa correlación de Pearson está diseñada para analizar la relación entre\nvariables cuantitativas continuas. Estas variables pueden asumir\ncualquier valor dentro de un intervalo determinado y suelen corresponder\na procesos de medición, como altura, peso corporal, índice de masa\ncorporal, temperatura o presión arterial.\n\nA diferencia de las variables cualitativas o discretas, las variables\ncontinuas permiten evaluar cambios graduales en los valores observados,\nlo que facilita el estudio de relaciones lineales entre ellas. Por esta\nrazón, antes de aplicar una correlación de Pearson es importante\nverificar que ambas variables correspondan a mediciones cuantitativas\ncontinuas.\n\nEn el presente ejemplo, las variables altura (cm) y peso corporal (kg)\ncumplen este supuesto, ya que representan mediciones físicas obtenidas\nen una escala numérica continua.\n\n### Prueba de normalidad Shapiro-Wilk\n\nLa prueba de Shapiro-Wilk permite evaluar si una variable cuantitativa\npresenta una distribución aproximadamente normal. En este caso, se\nanalizan las variables altura y peso corporal de los estudiantes.\n\nLa hipótesis nula ($H_0$) establece que los datos siguen una\ndistribución normal, mientras que la hipótesis alternativa ($H_1$)\nplantea que la distribución no es normal.\n\nLa decisión se toma a partir del valor $p$:\n\n-   si $p > 0.05$, no se rechaza la normalidad;\n\n-   si $p \\leq 0.05$, se concluye que la variable no presenta\n    distribución normal.\n\nEstas pruebas son importantes porque muchas técnicas estadísticas\nparamétricas, como la correlación de Pearson y la regresión lineal,\nasumen normalidad en los datos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(dplyr)\nlibrary(purrr)\n\n# Cargar base de datos\ndatos <- read_excel(\n  \"data/bd_antropometricas.xlsx\"\n)\n\n# Seleccionar variables numéricas\nvariables_numericas <- datos %>%\n  \n  select(where(is.numeric))\n\n# Aplicar Shapiro-Wilk a cada variable\nnormalidad <- map_df(\n  \n  names(variables_numericas),\n  \n  ~{\n    \n    prueba <- shapiro.test(\n      na.omit(variables_numericas[[.x]])\n    )\n    \n    data.frame(\n      Variable = .x,\n      W = round(prueba$statistic, 4),\n      p_value = round(prueba$p.value, 6),\n      \n      Normalidad = ifelse(\n        prueba$p.value > 0.05,\n        \"Sí presenta normalidad\",\n        \"No presenta normalidad\"\n      )\n    )\n  }\n)\n\n# Mostrar resultados\nnormalidad\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Variable      W  p_value             Normalidad\nW...1           Altura_cm 0.9753 0.000172 No presenta normalidad\nW...2             Peso_Kg 0.9040 0.000000 No presenta normalidad\nW...3  Anchura_hombros_cm 0.8824 0.000000 No presenta normalidad\nW...4        Long_Mano_cm 0.2747 0.000000 No presenta normalidad\nW...5        Lon_Palma_cm 0.9460 0.000000 No presenta normalidad\nW...6      Ancho_Palma_cm 0.9310 0.000000 No presenta normalidad\nW...7       Long_Brazo_cm 0.7635 0.000000 No presenta normalidad\nW...8   Long_Antebrazo_cm 0.7616 0.000000 No presenta normalidad\nW...9      Long_Pierna_cm 0.9950 0.564763 Sí presenta normalidad\nW...10        Long_Pie_cm 0.9914 0.134404 Sí presenta normalidad\n```\n\n\n:::\n:::\n\n\n### Independencia de las observaciones\n\nLa correlación de Pearson asume que cada observación es independiente de\nlas demás. Esto significa que el valor registrado para un individuo no\ndebe influir sobre los valores observados en otro individuo.\n\nEste supuesto depende principalmente del diseño de recolección de los\ndatos. En estudios donde cada participante aporta una única medición,\ncomo ocurre con la altura y el peso corporal de los estudiantes,\ngeneralmente se considera que existe independencia entre las\nobservaciones.\n\n### Relación lineal\n\nLa correlación de Pearson evalúa exclusivamente relaciones lineales\nentre variables. Por ello, antes de calcular el coeficiente de\ncorrelación es recomendable construir un diagrama de dispersión para\nverificar que los datos presentan una tendencia aproximadamente recta.\n\nDe manera general, una relación lineal puede representarse mediante la\necuación: $Y=β_0​+β_1​X$\n\ndonde:\n\n-   ($Y$) representa la variable dependiente;\n\n-   ($X$) corresponde a la variable independiente;\n\n-   ($β_0$) es el intercepto;\n\n-   ($β_1$) representa la pendiente de la relación.\n\nCuando la relación es lineal, un incremento en una variable tiende a\nestar asociado con un incremento o disminución proporcional en la otra\nvariable. Si la relación presenta formas curvas o patrones complejos, la\ncorrelación de Pearson puede subestimar la verdadera asociación\nexistente.\n\nEn este ejemplo, la linealidad puede evaluarse visualmente mediante el\ndiagrama de dispersión entre altura y peso corporal.\n\n### Regresión lineal simple\n\nLa **regresión lineal simple** estudia la relación entre una variable\nrespuesta ($Y$) y **una única variable explicativa** ($X$). Su forma\ngeneral es:\n\n$$\nY = \\beta_0 + \\beta_1X + \\varepsilon\n$$\n\ndonde $\\beta_0$ representa el intercepto, $\\beta_1$ cuantifica el cambio\nesperado en $Y$ por cada unidad de cambio en $X$, y $\\varepsilon$\nrepresenta el componente aleatorio no explicado por el modelo. En este\ncapítulo, la relación entre altura y peso corporal se utiliza como\nejemplo de regresión lineal simple porque interviene una sola variable\npredictora: la altura.\n\nEsta denominación permite diferenciarla de la **regresión lineal\nmúltiple**, que incorpora dos o más variables explicativas en un mismo\nmodelo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Modelo de regresión lineal simple\nmodelo <- lm(\n  Peso_Kg ~ Altura_cm,\n  data = datos\n)\n\n# Coeficientes\nb0 <- coef(modelo)[1]\nb1 <- coef(modelo)[2]\n\n# R²\nr2 <- summary(modelo)$r.squared\n\n# Gráfico\nplot(\n  datos$Altura_cm,\n  datos$Peso_Kg,\n  main = \"Relación entre altura y peso corporal\",\n  xlab = \"Altura (cm)\",\n  ylab = \"Peso (kg)\",\n  pch = 19,\n  col = \"blue\"\n)\n\n# Línea de regresión\nabline(\n  modelo,\n  col = \"red\",\n  lwd = 2\n)\n\n# Ecuación y R²\nlegend(\n  \"topright\",\n  legend = c(\n    paste0(\n      \"Peso = \",\n      round(b0,2),\n      \" + \",\n      round(b1,2),\n      \"(Altura)\"\n    ),\n    paste0(\n      \"R² = \",\n      round(r2,3)\n    )\n  ),\n  bty = \"n\"\n)\n```\n\n::: {.cell-output-display}\n![](07-analisis-bivariado_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n**Interpretación:** La ecuación de regresión obtenida fue:\n$\\hat{Peso} = \\beta_0 + \\beta_1(Altura)$, donde $\\beta_0$​ representa el\nintercepto y $\\beta_1$​ el cambio esperado en el peso corporal por cada\ncentímetro adicional de altura. El coeficiente de determinación ($R^2$)\nindica la proporción de variabilidad del peso explicada por la altura.\nValores cercanos a 0 sugieren una relación débil, mientras que valores\ncercanos a 1 indican una relación fuerte. De acuerdo con lo anterior el\ndiagrama de dispersión muestra una **tendencia positiva** entre la\naltura y el peso corporal de los estudiantes. En términos generales, a\nmedida que aumenta la altura, el peso también tiende a incrementarse.\n\nLa ecuación de regresión obtenida fue: $\\hat{Peso}=-77.62+0.79(Altura)$.\nEsto significa que, en promedio, por cada centímetro adicional de\naltura, el peso corporal aumenta aproximadamente **0.79 kg**.\n\nEl coeficiente de determinación fue: $R^2 = 0.16$, Lo que indica que la\naltura explica aproximadamente el **16 % de la variabilidad observada en\nel peso corporal**. El 84 % restante se debe a otros factores no\nincluidos en el modelo, como sexo, composición corporal, hábitos\nalimentarios, actividad física y variabilidad individual.\n\nVisualmente, la nube de puntos presenta una tendencia ascendente\ncompatible con una relación lineal positiva; sin embargo, la dispersión\nde los datos alrededor de la recta es relativamente amplia, lo que\nsugiere que la relación entre ambas variables es **débil a moderada**.\n\n### Regresión lineal múltiple\n\nLa diferencia central entre ambos modelos se encuentra en el número de\nvariables explicativas. La **regresión lineal simple** utiliza una sola\nvariable predictora, mientras que la **regresión lineal múltiple**\nincorpora dos o más predictores para explicar conjuntamente el\ncomportamiento de la variable respuesta.\n\n| Modelo | Número de variables explicativas | Forma general |\n|----|---:|----|\n| Regresión lineal simple | 1 | $Y = \\beta_0 + \\beta_1X + \\varepsilon$ |\n| Regresión lineal múltiple | 2 o más | $Y = \\beta_0 + \\beta_1X_1 + \\cdots + \\beta_kX_k + \\varepsilon$ |\n\nMuchos fenómenos reales dependen simultáneamente de varios factores, por\nlo que resulta necesario incorporar múltiples variables predictoras\ndentro del modelo. La regresión lineal múltiple puede expresarse como:\n\n$Y=\\beta_0+\\beta_1X_1+\\beta_2X_2+\\cdots+\\beta_kX_k$\n\ndonde:\n\n\\- $Y$: variable respuesta o dependiente.\\\n- $\\beta_0$: intercepto del modelo.\\\n- $X_1, X_2, \\ldots, X_k$: variables explicativas o predictoras.\\\n- $\\beta_1, \\beta_2, \\ldots, \\beta_k$: coeficientes asociados a cada\npredictor.\n\nEn este contexto, el supuesto de linealidad implica que cada variable\nexplicativa mantiene una relación lineal con la variable respuesta, una\nvez controlado el efecto de las demás variables incluidas en el modelo.\n\nPor ejemplo, en la base antropométrica el peso corporal podría modelarse\nutilizando simultáneamente variables como la altura, la longitud de la\npierna, la longitud del pie, la longitud de la mano, el índice de masa\ncorporal (IMC) y el sexo. De esta manera, el modelo permite evaluar el\naporte específico de cada característica sobre el peso corporal,\nmanteniendo constantes las demás variables.\n\n$Peso=β_0​+β_1​(Altura)+β_2​(LongitudPierna)+β_3​(LongitudPie)+β_4​(LongitudMano)+β_5​(IMC)$\n\no incluso:\n\n$Altura=β_0+β_1(Longitud  Pierna)+β_2(Longitud  Pie)+β_3(Longitud  Mano)$\n\n### Homocedasticidad\n\nLa homocedasticidad indica que la variabilidad de una variable se\nmantiene relativamente constante a lo largo de los valores de la otra\nvariable. Por ejemplo:\n\n-   altura baja → dispersión similar\n\n-   altura media → dispersión similar\n\n-   altura alta → dispersión similar\n\nLa homocedasticidad implica que la varianza de los errores es constante\npara todos los valores de la variable independiente:\n\n$Var(\\varepsilon_i)=\\sigma^2$\n\ndonde:\n\n$ε_i$: error o residuo de la observación $i$;\n\n$\\sigma^2$: varianza constante de los errores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo <- lm(\n  Peso_Kg ~ Altura_cm,\n  data = datos\n)\n\nplot(\n  fitted(modelo),\n  residuals(modelo),\n  main = \"Residuos vs Valores ajustados\",\n  xlab = \"Valores ajustados\",\n  ylab = \"Residuos\",\n  pch = 19,\n  col = \"darkgreen\"\n)\n\nabline(\n  h = 0,\n  col = \"red\",\n  lwd = 2\n)\n```\n\n::: {.cell-output-display}\n![](07-analisis-bivariado_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n**Interpretación:** La homocedasticidad hace referencia a la igualdad\naproximada de la variabilidad de los datos a lo largo de los diferentes\nvalores de la variable independiente. Este supuesto es importante porque\nmuchas técnicas paramétricas asumen que la dispersión de los errores\npermanece constante.\n\nLa evaluación visual puede realizarse mediante un gráfico de residuos\nfrente a los valores ajustados. Cuando los residuos se distribuyen\naleatoriamente alrededor de cero y mantienen una amplitud similar en\ntodo el rango de observaciones, se considera que existe\nhomocedasticidad. Por el contrario, si la dispersión aumenta o disminuye\nsistemáticamente formando patrones de abanico o embudo, podría existir\nheterocedasticidad, indicando que la variabilidad de los errores no es\nconstante.\n\n### Ausencia de valores atípicos extremos\n\nLos valores atípicos extremos (outliers) pueden afectar\nsignificativamente el coeficiente de correlación de Pearson, generando\nestimaciones sesgadas o conclusiones incorrectas sobre la intensidad de\nla relación entre las variables.\n\nPara identificar posibles valores atípicos se recomienda utilizar\ndiagramas de caja (boxplots) o diagramas de dispersión. Si se detectan\nobservaciones extremas, estas deben revisarse cuidadosamente para\ndeterminar si corresponden a errores de registro o a valores reales de\nla población estudiada.\n\nLa presencia de valores atípicos no implica necesariamente su\neliminación, pero sí requiere una evaluación crítica antes de realizar\nel análisis estadístico.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\n\ndatos <- read_excel(\n  \"data/bd_antropometricas.xlsx\"\n)\n\nboxplot(\n  datos$Peso_Kg,\n  main = \"Distribución del peso corporal\",\n  ylab = \"Peso (kg)\",\n  col = \"lightblue\"\n)\n```\n\n::: {.cell-output-display}\n![](07-analisis-bivariado_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## Estructura general para seleccionar la técnica adecuada\n\nEn el análisis de asociación, la selección de la técnica estadística\ndepende principalmente del tipo de variables que se desean analizar, del\nobjetivo del estudio y de los supuestos que cumplen los datos\n(@fig-dosvariables). Por esta razón, antes de aplicar cualquier\nprocedimiento es necesario identificar si las variables son\ncuantitativas o categóricas, revisar su distribución, explorar la forma\nde la relación y verificar la presencia de valores atípicos.\n\n![Esquema para la selección de técnicas de análisis de asociación según\nla naturaleza de las\nvariables.](img/dosvariables.png){#fig-dosvariables}\n\n## Cuando se cumplen los supuestos\n\nEn el caso de las variables **Long_Pierna_cm** y **Long_Pie_cm**\npresentan un comportamiento compatible con una distribución normal según\nla prueba de Shapiro-Wilk.\n\nPara la variable **Long_Pierna_cm**, se obtuvo un estadístico\n$W = 0.9950$ y un valor $p = 0.564763$. Debido a que el valor $p$ es\nmayor que $0.05$, no se rechaza la hipótesis nula de normalidad. Esto\nindica que la distribución de la longitud de la pierna no presenta\ndiferencias significativas respecto a una distribución normal.\n\nDe manera similar, la variable **Long_Pie_cm** presentó un estadístico\n$W = 0.9914$ y un valor $p = 0.134404$. Al ser también mayor que $0.05$,\nse concluye que la longitud del pie presenta una distribución\naproximadamente normal.\n\nEn términos prácticos, estos resultados sugieren que ambas variables\nantropométricas poseen distribuciones relativamente simétricas y sin\ndesviaciones extremas importantes, lo cual favorece la aplicación de\ntécnicas estadísticas paramétricas, como: correlación de Pearson,\npruebas t, análisis de regresión lineal e intervalos de confianza\nbasados en normalidad.\n\nAsimismo, el comportamiento normal de estas variables es coherente con\nmuchas mediciones biológicas y antropométricas, donde las\ncaracterísticas físicas de una población suelen distribuirse alrededor\nde un valor promedio central.\n\n### Correlación de Pearson\n\nLa correlación es una medida estadística utilizada para cuantificar la\nfuerza y la dirección de la relación entre dos variables cuantitativas.\nA diferencia del diagrama de dispersión, que permite explorar\nvisualmente el comportamiento conjunto de las variables, la correlación\nresume dicha relación mediante un valor numérico (@fig-correlacion). El\ncoeficiente de correlación de Pearson se calcula como:\n\n$$\nr = \\frac{\\sum_{i=1}^{n}(x_i-\\bar{x})(y_i-\\bar{y})}\n{\\sqrt{\\sum_{i=1}^{n}(x_i-\\bar{x})^2 \\sum_{i=1}^{n}(y_i-\\bar{y})^2}}\n$$\n\nEl coeficiente de correlación indica qué tan estrechamente se relacionan\ndos variables y si dicha relación es positiva, negativa o inexistente.\n\n#### De la covarianza a la correlación\n\nLa relación entre ambos conceptos puede expresarse de manera directa: la\n**correlación de Pearson es una covarianza estandarizada**. En su forma\nmuestral:\n\n$$\nr_{XY}=\\frac{\\operatorname{Cov}(X,Y)}{s_Xs_Y}\n$$\n\nEl **numerador** corresponde a la covarianza entre $X$ y $Y$, que\nrefleja el sentido en que ambas variables varían conjuntamente. El\n**denominador** corresponde al producto de sus desviaciones estándar y\nactúa como un factor de estandarización. Gracias a esta estandarización,\nel coeficiente de correlación no depende de las unidades originales de\nmedida y queda acotado entre $-1$ y $1$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Relación conceptual entre la covarianza y la correlación de Pearson.](07-analisis-bivariado_files/figure-html/fig-cov-correlacion-1.png){#fig-cov-correlacion width=672}\n:::\n:::\n\n\n::: callout-note\n## Idea clave\n\nLa covarianza y la correlación describen la variación conjunta de dos\nvariables, pero **no son equivalentes**. La covarianza conserva las\nunidades de las variables y no posee límites fijos; por ello, su\nmagnitud no debe interpretarse como si estuviera en una escala de $-1$ a\n$1$. La correlación divide la covarianza por el producto de las\ndesviaciones estándar y produce una medida adimensional comparable entre\ndiferentes pares de variables.\n:::\n\n![Escala conceptual para interpretar la dirección y magnitud de un\ncoeficiente de correlación.](img/correlacion.png){#fig-correlacion}\n\n#### Ejemplo en R\n\nEn el siguiente ejemplo se calcula la correlación entre altura y peso\ncorporal utilizando la base de datos antropométrica.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(ggplot2)\n\n# Cargar base de datos\ndatos <- read_excel(\n  \"data/bd_antropometricas.xlsx\"\n)\n\n# Calcular correlación\nr <- cor(\n  datos$Long_Pierna_cm,\n  datos$Long_Pie_cm,\n  \n  method = \"pearson\",\n  \n  use = \"complete.obs\"\n)\n\n# Gráfico\nggplot(\n  datos,\n  \n  aes(\n    x = Long_Pierna_cm,\n    y = Long_Pie_cm,\n    color = Genero\n  )\n) +\n  \n  geom_point(\n    size = 3,\n    alpha = 0.75\n  ) +\n  \n  scale_color_manual(\n    values = c(\n      \"F\" = \"#D95F02\",\n      \"M\" = \"#1B9E77\"\n    )\n  ) +\n  \n  geom_smooth(\n    method = \"lm\",\n    se = FALSE,\n    color = \"black\",\n    linewidth = 1\n  ) +\n  \n  annotate(\n    \"text\",\n    \n    x = min(datos$Long_Pierna_cm) + 5,\n    \n    y = max(datos$Long_Pie_cm) - 5,\n    \n    label = paste0(\n      \"r = \",\n      round(r, 3)\n    ),\n    \n    size = 5,\n    \n    fontface = \"bold\",\n    \n    color = \"black\"\n  ) +\n  \n  labs(\n    title = \"Relación entre Longitud Pierna y Longitud pie\",\n    \n    subtitle = \"Diagrama de dispersión y correlación de Pearson\",\n    \n    x = \"Longitud Pierna (cm)\",\n    \n    y = \"Longitud pie (cm)\",\n    \n    color = \"Género\",\n    \n    caption = \"Fuente: Base de datos antropométrica, Miguel Oswaldo Pérez Pulido (UDES)\"\n  ) +\n  \n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](07-analisis-bivariado_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n**Interpretación:** El diagrama de dispersión permite explorar la\nrelación entre la longitud de la pierna y la longitud del pie en los\nestudiantes, diferenciando las observaciones según el género.\nVisualmente, los puntos se encuentran ampliamente dispersos y no\nmuestran una tendencia lineal clara entre ambas variables.\n\nEl **coeficiente de correlación de Pearson** obtenido ($r = 0.012$)\nindica una **asociación lineal prácticamente nula entre la longitud de\nla pierna y la longitud del pie**. Este valor, al encontrarse muy\ncercano a cero, sugiere que el aumento en una de las variables no se\nrelaciona de manera consistente con cambios en la otra dentro de la\nmuestra analizada.\n\nAsimismo, la línea de tendencia horizontal observada en el gráfico\nconfirma la ausencia de una relación lineal significativa. Aunque\nexisten diferencias naturales entre hombres y mujeres en la distribución\nde las observaciones, dichas variaciones no generan un patrón de\nasociación fuerte entre las variables estudiadas.\n\nEn términos prácticos, estos resultados indican que la longitud de la\npierna no constituye un buen predictor lineal de la longitud del pie en\nesta población específica. Este tipo de análisis es importante porque\ndemuestra que no todas las variables antropométricas presentan\nrelaciones lineales fuertes, incluso cuando pertenecen a una misma\ndimensión biológica.\n\n## Cuando no se cumplen los supuestos\n\n**Interpretación Altura_cm y Peso_Kg:** La prueba de Shapiro-Wilk indica\nque ninguna de las dos variables presenta una distribución normal al\nnivel de significancia del 5 %.\n\nPara la variable **Altura_cm**, se obtuvo un estadístico $W = 0.9752$ y\nun valor $p = 0.000171$. Debido a que el valor $p$ es menor que $0.05$,\nse rechaza la hipótesis nula de normalidad, concluyendo que la\ndistribución de la altura difiere significativamente de una distribución\nnormal.\n\nDe manera similar, para la variable **Peso_Kg**, el estadístico obtenido\nfue $W = 0.9040$ con un valor $p = 7.916 \\times 10^{-12}$, valor\nextremadamente pequeño que también conduce al rechazo de la hipótesis de\nnormalidad. Esto indica que la distribución del peso corporal presenta\ndesviaciones importantes respecto a la normalidad.\n\nEn términos prácticos, estos resultados sugieren que las variables\nantropométricas analizadas no cumplen completamente el supuesto de\nnormalidad requerido por algunas técnicas paramétricas. Por esta razón,\nen determinados contextos podría ser recomendable complementar el\nanálisis utilizando métodos no paramétricos, como la correlación de\nSpearman, especialmente si existen valores extremos o distribuciones\nasimétricas.\n\n### Correlación de Spearman\n\nLa correlación de Spearman es una medida estadística utilizada para\nevaluar la asociación entre dos variables ordinales o cuantitativas\ncuando no se cumplen los supuestos de normalidad o linealidad requeridos\npor la correlación de Pearson (@fig-corspearman).\n\nA diferencia de Pearson, Spearman no trabaja directamente con los\nvalores originales de las variables, sino con sus rangos o posiciones\ndentro de la distribución. Por esta razón, se considera una medida no\nparamétrica de asociación.\n\n![Esquema conceptual de la correlación de Spearman basada en\nrangos.](img/corspearman.png){#fig-corspearman}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(ggplot2)\nlibrary(dplyr)\n\n# Cargar base de datos\ndatos <- read_excel(\n  \"data/bd_antropometricas.xlsx\"\n)\n\n# Correlación por género\ndatos %>%\n  \n  group_by(Genero) %>%\n  \n  summarise(\n    Correlacion = cor(\n      Altura_cm,\n      Peso_Kg,\n      \n      method = \"spearman\",\n      \n      use = \"complete.obs\"\n    )\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  Genero Correlacion\n  <chr>        <dbl>\n1 F           0.0657\n2 M           0.178 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Diagrama de dispersión por género\nggplot(\n  datos,\n  \n  aes(\n    x = Altura_cm,\n    y = Peso_Kg,\n    color = Genero\n  )\n) +\n  \n  geom_point(\n    size = 3,\n    alpha = 0.75\n  ) +\n  \n  geom_smooth(\n    method = \"lm\",\n    se = FALSE,\n    linewidth = 1\n  ) +\n  \n  scale_color_manual(\n    values = c(\n      \"F\" = \"#D95F02\",\n      \"M\" = \"#1B9E77\"\n    )\n  ) +\n  \n  labs(\n    title = \"Relación entre altura y peso corporal según género\",\n    \n    subtitle = \"Comparación de patrones de asociación\",\n    \n    x = \"Altura (cm)\",\n    \n    y = \"Peso (kg)\",\n    \n    color = \"Género\",\n    \n    caption = \"Fuente: Base de datos antropométrica, Miguel Oswaldo Pérez Pulido (UDES)\"\n  ) +\n  \n  theme_minimal(base_size = 12) +\n  \n  theme(\n    plot.title = element_text(\n      face = \"bold\",\n      size = 15\n    ),\n    \n    plot.subtitle = element_text(\n      size = 11\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](07-analisis-bivariado_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Otras herramientas para explorar la asociación\n\n### Diagrama de dispersión\n\nEl diagrama de dispersión, también conocido como nube de puntos, es una\nrepresentación gráfica utilizada para explorar la relación entre dos\nvariables cuantitativas. Cada punto del gráfico representa una\nobservación y su posición en el plano cartesiano depende de los valores\nregistrados para las variables $X$ y $Y$.\n\nEsta herramienta constituye generalmente el primer paso del análisis de\nasociación entre variables cuantitativas, ya que permite identificar\nvisualmente patrones, tendencias, agrupamientos y posibles valores\natípicos antes de aplicar medidas numéricas de correlación o modelos de\nregresión (@fig-dispersion). A partir de un diagrama de dispersión\npueden identificarse diferentes comportamientos entre las variables:\n\n![Ejemplos de patrones de asociación que pueden observarse en diagramas\nde dispersión.](img/dispersion.png){#fig-dispersion}\n\n#### Ejemplo en R\n\nEn el siguiente ejemplo se utiliza la base de datos antropométrica para\nanalizar la relación entre la estatura de los estudiantes y su peso\ncorporal. El objetivo consiste en explorar visualmente si existe\nasociación entre ambas variables mediante un diagrama de dispersión.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(ggplot2)\n\n# Cargar base de datos\ndatos <- read_excel(\n  \"data/bd_antropometricas.xlsx\"\n)\n\n# Diagrama de dispersión\nggplot(\n  datos,\n  \n  aes(\n    x = Altura_cm,\n    y = Peso_Kg,\n    color = Genero\n  )\n) +\n  \n  geom_point(\n    size = 3,\n    alpha = 0.75\n  ) +\n  \n  scale_color_manual(\n    values = c(\n      \"F\" = \"#D95F02\",\n      \"M\" = \"#1B9E77\"\n    )\n  ) +\n  \n  labs(\n    title = \"Relación entre altura y peso corporal\",\n    \n    subtitle = \"Distribución según género\",\n    \n    x = \"Altura (cm)\",\n    \n    y = \"Peso (kg)\",\n    \n    color = \"Género\",\n    \n    caption = \"Fuente: Base de datos antropométrica, Miguel Oswaldo Pérez Pulido (UDES)\"\n  ) +\n  \n  theme_minimal(base_size = 12) +\n  \n  theme(\n    plot.title = element_text(\n      face = \"bold\",\n      size = 15\n    ),\n    \n    plot.subtitle = element_text(\n      size = 11\n    ),\n    \n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](07-analisis-bivariado_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Interpretación:** El diagrama de dispersión permite explorar\nvisualmente la relación entre la altura y el peso corporal de los\nestudiantes, diferenciando las observaciones según el género. En\ngeneral, se observa una tendencia positiva entre ambas variables,\nindicando que a mayores valores de altura tienden a presentarse mayores\nvalores de peso corporal.\n\nLa diferenciación por color facilita identificar posibles agrupamientos\nentre hombres y mujeres, evidenciando patrones distintos en la\ndistribución de las observaciones. Este tipo de visualización resulta\nútil para detectar comportamientos particulares dentro de subgrupos\npoblacionales y constituye una herramienta exploratoria fundamental\nantes de aplicar medidas numéricas de asociación o modelos estadísticos\nmás complejos.\n\n::: callout-warning\nEl **diagrama de dispersión** es principalmente una herramienta de\nanálisis exploratorio y visualización bivariada. NO es todavía una\ncorrelación numérica.\n:::\n\n### Covarianza\n\nLa covarianza es una medida estadística utilizada para evaluar cómo\nvarían conjuntamente dos variables cuantitativas respecto a sus medias.\nEsta medida permite identificar si ambas variables tienden a aumentar\nsimultáneamente, disminuir conjuntamente o comportarse de manera\nindependiente (@fig-covarianza).\n\nLa covarianza constituye uno de los fundamentos matemáticos de la\ncorrelación lineal y de la regresión. Para una muestra, puede expresarse\ncomo:\n\n$$\ns_{XY}=\\frac{1}{n-1}\\sum_{i=1}^{n}(x_i-\\bar{x})(y_i-\\bar{y})\n$$\n\nEsta expresión muestra que cada observación aporta a la covarianza a\ntravés del producto $(x_i-\\bar{x})(y_i-\\bar{y})$. La posición de cada\npunto respecto a las medias de $X$ y $Y$ permite interpretar el signo de\nesa contribución:\n\n| Cuadrante respecto a $\\bar{x}$ y $\\bar{y}$ | Signos | Contribución al producto |\n|----|----|----|\n| Superior derecho (I) | $(+)(+)$ | Positiva |\n| Superior izquierdo (II) | $(-)(+)$ | Negativa |\n| Inferior izquierdo (III) | $(-)(-)$ | Positiva |\n| Inferior derecho (IV) | $(+)(-)$ | Negativa |\n\nPor tanto, cuando predominan puntos en los cuadrantes I y III, la\ncovarianza tiende a ser positiva; cuando predominan en los cuadrantes II\ny IV, tiende a ser negativa. Si las contribuciones positivas y negativas\nse compensan, la covarianza puede aproximarse a cero.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Interpretación geométrica de la covarianza. Las líneas representan las medias de X y Y; los cuadrantes I y III generan contribuciones positivas, mientras que II y IV generan contribuciones negativas.](07-analisis-bivariado_files/figure-html/fig-covarianza-cuadrantes-1.png){#fig-covarianza-cuadrantes width=960}\n:::\n:::\n\n\nLa figura permite observar que el **signo** de la covarianza está\nrelacionado con la ubicación de los puntos respecto a las medias. Sin\nembargo, su **magnitud depende de las unidades y de la escala** de las\nvariables. Por esta razón, no es correcto interpretar una covarianza\nnuméricamente grande o pequeña utilizando los límites $-1$ y $1$; esos\nlímites corresponden al coeficiente de correlación.\n\n![Esquema conceptual de la covarianza y de cómo dos variables pueden\nvariar conjuntamente.](img/covarianza.png){#fig-covarianza}\n\n#### Ejemplo en R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\n\n# Cargar base de datos\ndatos <- read_excel(\n  \"data/bd_antropometricas.xlsx\"\n)\n\n# Covarianza\ncov(\n  datos$Long_Pierna_cm,\n  datos$Long_Pie_cm,\n  \n  use = \"complete.obs\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06261345\n```\n\n\n:::\n:::\n\n\n**Interpretación:** La covarianza calculada\n($\\operatorname{Cov}(X,Y)=0.062$) entre la longitud de la pierna y la\nlongitud del pie tiene signo positivo, lo que indica que, en promedio,\nlas desviaciones de ambas variables respecto a sus medias tienden a\naportar en el mismo sentido. No obstante, **la magnitud de una\ncovarianza no debe interpretarse directamente como fuerte o débil**,\nporque depende de las unidades y escalas de las variables analizadas.\n\nPara valorar la fuerza de la asociación en una escala estandarizada se\nutiliza el **coeficiente de correlación de Pearson**. En este caso, el\nvalor previamente obtenido ($r = 0.012$) se encuentra muy próximo a cero\ny evidencia una asociación lineal prácticamente nula entre las\nvariables. La comparación permite observar la relación conceptual entre\nambas medidas: la covarianza aporta la variación conjunta en el\nnumerador y la correlación la estandariza mediante las desviaciones\nestándar.\n\nAsimismo, este ejemplo permite comprender que no todas las variables\nantropométricas presentan asociaciones lineales fuertes, incluso cuando\npertenecen a dimensiones corporales relacionadas.\n\n### Tablas de contingencia\n\nLas tablas de contingencia son herramientas estadísticas utilizadas para\nresumir y analizar la relación entre dos variables categóricas. Estas\ntablas permiten organizar las frecuencias observadas según las\ndiferentes combinaciones de categorías presentes en las variables\nestudiadas.\n\nTambién son conocidas como: tablas cruzadas, tablas de doble entrada o\ntablas de asociación.\n\nSu principal objetivo consiste en identificar posibles patrones de\nrelación o dependencia entre categorías.\n\n#### Estructura general\n\nUna tabla de contingencia distribuye las observaciones en filas y\ncolumnas:\n\n|              | Categoría B1 | Categoría B2 | Total        |\n|--------------|--------------|--------------|--------------|\n| Categoría A1 | $f_{11}$     | $f_{12}$     | $f_{1\\cdot}$ |\n| Categoría A2 | $f_{21}$     | $f_{22}$     | $f_{2\\cdot}$ |\n| Total        | $f_{\\cdot1}$ | $f_{\\cdot2}$ | $n$          |\n\ndonde:\n\n-   las filas representan categorías de una variable;\n-   las columnas representan categorías de la otra variable;\n-   cada celda contiene la frecuencia observada.\n\n### Interpretación\n\nLas tablas de contingencia permiten comparar frecuencias entre grupos;\nidentificar asociaciones entre categorías; calcular porcentajes\nconjuntos; analizar patrones poblacionales; servir como base para\npruebas como Chi-cuadrado. Cuando las proporciones observadas son\nsimilares entre categorías, puede inferirse independencia entre las\nvariables. En cambio, diferencias importantes sugieren posibles\nasociaciones.\n\n### Ejercicio contextual\n\nEn estudios educativos puede analizarse la relación entre género y\naprobación académica; modalidad de estudio y rendimiento o nivel\nsocioeconómico y acceso tecnológico. En salud tabaquismo y enfermedad;\nclasificación nutricional y actividad física.\n\n### Ejemplo en R\n\nEn el siguiente ejemplo se construye una tabla de contingencia entre\ngénero y grupo académico utilizando la base antropométrica.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(dplyr)\nlibrary(janitor)\nlibrary(knitr)\nlibrary(kableExtra)\n\n# Cargar base de datos\ndatos <- read_excel(\n  \"data/bd_antropometricas.xlsx\"\n)\n\n#====================================================\n# 1. Género vs Talla dicotómica\n#====================================================\n\ndatos %>%\n  \n  tabyl(\n    Genero,\n    Talla_Dicotica\n  ) %>%\n  \n  adorn_totals(c(\"row\", \"col\")) %>%\n  \n  adorn_percentages(\"row\") %>%\n  \n  adorn_pct_formatting(digits = 1) %>%\n  \n  adorn_ns(position = \"front\") %>%\n  \n  kable(\n    caption = \"Tabla de contingencia: Género y talla dicotómica\",\n    align = \"c\"\n  ) %>%\n  \n  kable_styling(\n    full_width = FALSE,\n    bootstrap_options = c(\n      \"striped\",\n      \"hover\",\n      \"condensed\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Tabla de contingencia: Género y talla dicotómica</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Genero </th>\n   <th style=\"text-align:center;\"> Alta </th>\n   <th style=\"text-align:center;\"> Baja </th>\n   <th style=\"text-align:center;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> F </td>\n   <td style=\"text-align:center;\"> 23 (11.1%) </td>\n   <td style=\"text-align:center;\"> 185 (88.9%) </td>\n   <td style=\"text-align:center;\"> 208 (100.0%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> M </td>\n   <td style=\"text-align:center;\"> 30 (57.7%) </td>\n   <td style=\"text-align:center;\"> 22 (42.3%) </td>\n   <td style=\"text-align:center;\"> 52 (100.0%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Total </td>\n   <td style=\"text-align:center;\"> 53 (20.4%) </td>\n   <td style=\"text-align:center;\"> 207 (79.6%) </td>\n   <td style=\"text-align:center;\"> 260 (100.0%) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\n#====================================================\n# 2. Género vs IMC dicotómico\n#====================================================\n\ndatos %>%\n  \n  tabyl(\n    Genero,\n    IMC_Dicotico\n  ) %>%\n  \n  adorn_totals(c(\"row\", \"col\")) %>%\n  \n  adorn_percentages(\"row\") %>%\n  \n  adorn_pct_formatting(digits = 1) %>%\n  \n  adorn_ns(position = \"front\") %>%\n  \n  kable(\n    caption = \"Tabla de contingencia: Género e IMC dicotómico\",\n    align = \"c\"\n  ) %>%\n  \n  kable_styling(\n    full_width = FALSE,\n    bootstrap_options = c(\n      \"striped\",\n      \"hover\",\n      \"condensed\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Tabla de contingencia: Género e IMC dicotómico</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Genero </th>\n   <th style=\"text-align:center;\"> Bajo_Peso </th>\n   <th style=\"text-align:center;\"> Normal+ </th>\n   <th style=\"text-align:center;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> F </td>\n   <td style=\"text-align:center;\"> 127 (61.1%) </td>\n   <td style=\"text-align:center;\"> 81 (38.9%) </td>\n   <td style=\"text-align:center;\"> 208 (100.0%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> M </td>\n   <td style=\"text-align:center;\"> 10 (19.2%) </td>\n   <td style=\"text-align:center;\"> 42 (80.8%) </td>\n   <td style=\"text-align:center;\"> 52 (100.0%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Total </td>\n   <td style=\"text-align:center;\"> 137 (52.7%) </td>\n   <td style=\"text-align:center;\"> 123 (47.3%) </td>\n   <td style=\"text-align:center;\"> 260 (100.0%) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\n#====================================================\n# 3. Género vs Tamaño de mano\n#====================================================\n\ndatos %>%\n  \n  tabyl(\n    Genero,\n    Mano_Dicotica\n  ) %>%\n  \n  adorn_totals(c(\"row\", \"col\")) %>%\n  \n  adorn_percentages(\"row\") %>%\n  \n  adorn_pct_formatting(digits = 1) %>%\n  \n  adorn_ns(position = \"front\") %>%\n  \n  kable(\n    caption = \"Tabla de contingencia: Género y tamaño de mano\",\n    align = \"c\"\n  ) %>%\n  \n  kable_styling(\n    full_width = FALSE,\n    bootstrap_options = c(\n      \"striped\",\n      \"hover\",\n      \"condensed\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Tabla de contingencia: Género y tamaño de mano</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Genero </th>\n   <th style=\"text-align:center;\"> Grande </th>\n   <th style=\"text-align:center;\"> Pequeña </th>\n   <th style=\"text-align:center;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> F </td>\n   <td style=\"text-align:center;\"> 26 (12.5%) </td>\n   <td style=\"text-align:center;\"> 182 (87.5%) </td>\n   <td style=\"text-align:center;\"> 208 (100.0%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> M </td>\n   <td style=\"text-align:center;\"> 38 (73.1%) </td>\n   <td style=\"text-align:center;\"> 14 (26.9%) </td>\n   <td style=\"text-align:center;\"> 52 (100.0%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Total </td>\n   <td style=\"text-align:center;\"> 64 (24.6%) </td>\n   <td style=\"text-align:center;\"> 196 (75.4%) </td>\n   <td style=\"text-align:center;\"> 260 (100.0%) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Interpretación:** En términos generales, el 88.9 % de las mujeres se\nclasifican dentro del rango normal de IMC y el 11.1 % presenta sobrepeso\nu obesidad. En contraste, entre los hombres solo el 48.1 % presenta IMC\nnormal, mientras que el 51.9 % se ubica en la categoría de\nsobrepeso-obesidad. Considerando el total de la muestra, el 80.8 % de\nlos estudiantes presenta un IMC normal y el 19.2 % presenta sobrepeso u\nobesidad.\n\nEstos resultados sugieren una posible asociación entre el género y la\nclasificación del IMC, evidenciando una mayor proporción de\nsobrepeso-obesidad en los hombres respecto a las mujeres dentro de la\npoblación analizada. Las tablas de contingencia permiten identificar\neste tipo de patrones descriptivos y constituyen la base para\nposteriores análisis inferenciales, como la prueba Chi-cuadrado de\nindependencia.\n\n## Integración y aplicación\n\n### Estructura general para seleccionar la técnica adecuada\n\n### Laboratorio experiencial\n\n**¿Existe relación entre la altura y el peso corporal?**\n\n**Situación problema:** Un grupo de estudiantes de fisioterapia desea\nanalizar si la altura corporal se relaciona con el peso de los\nestudiantes universitarios. Para ello, se recolectó información\nantropométrica de hombres y mujeres de diferentes semestres académicos.\n\n**Objetivo del análisis**\n\nDeterminar: si existe relación entre altura y peso; la dirección de la\nrelación; la fuerza de la asociación y si el género modifica visualmente\nel comportamiento de los datos.\n\n### Actividades del estudiante\n\n**Parte 1 — Exploración visual**\n\n**Preguntas**\n\n¿Qué tipo de relación observa en el diagrama? positiva, negativa, nula,\ncurvilínea.\\\n¿La relación parece fuerte o débil?\\\n¿Existen valores atípicos?\\\n¿Se observan diferencias entre hombres y mujeres?\n\n**Parte 2 — Correlación**\n\nCalcule: correlación de Pearson y correlación de Spearman.\n\n**Preguntas**\n\n¿Los coeficientes son similares?\\\n¿Cuál considera más apropiado según la distribución de los datos?\\\n¿Puede afirmarse causalidad?\n\n**Parte 3 — Interpretación aplicada**\n\nUn investigador afirma que “Los estudiantes más altos necesariamente\npesan más”.\n\n**Preguntas críticas**\n\n¿La correlación encontrada permite afirmar eso?\n\n¿Qué limitaciones tiene el análisis?\n\n¿Qué otras variables podrían influir?\n",
    "supporting": [
      "07-analisis-bivariado_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}